name: CD Pipeline

on:
  workflow_run:
    workflows: ["Build and Deploy to Docker"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull degr8sidcode/myapp:latest
    - name: Delete Old docker container
      run: sudo docker rm -f myapp || true
    - name: Run Docker Container
      run: sudo docker run -d -p 8080:8080 --name myapp degr8sidcode/myapp
